<a href="https://colab.research.google.com/github/HWANG-HOE-SUN/Univ.Project/blob/main/%EC%A7%84%ED%95%B4Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **고장코드 有 변환 후**

### 데이터 불러오기

In [1]:
import os
from scipy import io
import numpy as np
import pandas as pd
import copy
import matplotlib.pyplot as plt
import re # 텍스트 검색(정규표현)
import struct
%matplotlib inline

In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [ ]:
path_dir = '/content/gdrive/MyDrive/DATA/고장코드 有_변환 후/27.진해_6033_200115_P1F0166,0066'
file_list = os.listdir(path_dir)

In [ ]:
for file in file_list:
  print(file)

진해_6033_20200114061311.mat
진해_6033_20200114065945.mat
진해_6033_20200114092858.mat
진해_6033_20200114115522.mat
진해_6033_20200114142250.mat
진해_6033_20200114164902.mat
진해_6033_20200114191610.mat
진해_6033_20200114211913.mat
진해_6033_20200115044101.mat
분할


In [ ]:
matfile14=[]
dist = path_dir+'/'+file_list[7] # file_list 1~6까진 분할파일에서 얻어야 함 (file size때문)
matfile14.append(io.loadmat(dist)) # 14일 

In [ ]:
feature_name = []
for file in matfile14:
  feature_name.append(list(file.keys()))
for i in feature_name:
  print(len(i))

1142


In [ ]:
test = pd.DataFrame(matfile14)

In [ ]:
col_len=[]
for i in range(len(test.T)):
  col_len.append(len(test.iloc[0,i]))

In [ ]:
np.argmax(col_len) # 최대 시간 길이를 가진 칼럼의 위치

47

In [ ]:
test.iloc[:,np.argmax(col_len)].iloc[0]

array([[240.1402 ,   0.     ],
       [240.1497 ,   0.     ],
       [240.1597 ,   0.     ],
       ...,
       [301.4632 ,   0.     ],
       [301.4732 ,   0.     ],
       [301.48315,   0.     ]])

In [ ]:
test.iloc[0,].iloc[0]

array([[2.40131550e+02, 2.01211479e-01],
       [2.40141650e+02, 2.01211479e-01],
       [2.40151550e+02, 2.01211479e-01],
       ...,
       [3.01458350e+02, 8.98832970e-02],
       [3.01468350e+02, 8.98832970e-02],
       [3.01478350e+02, 8.98832970e-02]])

# 데이터 통합

### 채널 길이 확인

In [ ]:
excel_path = '/content/gdrive/MyDrive/학부연구생/겹치는채널.xlsx'
useful_excel1 = pd.read_excel(excel_path,sheet_name=0)
useful_excel2 = pd.read_excel(excel_path,sheet_name=1)
useful_excel3 = pd.read_excel(excel_path,sheet_name=2)
useful_excel4 = pd.read_excel(excel_path,sheet_name=3)
useful_excel5 = pd.read_excel(excel_path,sheet_name=4)
useful_excel6 = pd.read_excel(excel_path,sheet_name=5)

In [ ]:
sig1 = useful_excel1['SignalName'][:-1]
useful_excel1['SignalName'][:-1] # 맨 뒤 제외 , 휠모터 고장 연관 채널

0             BM1__AxuInverter__Inv_Battery_V
1           BM1__AxuInverter__INV_Fault_Check
2              BM1__AxuInverter__Inv_IptVol_V
3              BM1__AxuInverter__INV_Power_kW
4         BM1__AxuInverter__Mot_ActRotSpd_rpm
                        ...                  
122    CCAN__VCU_EFD__CR_VCU_EVCoolantAuxTemp
123    CCAN__VCU_EFD__CR_VCU_EVCoolantMotTemp
124    CCAN__VCU_EFD__CR_VCU_EVCoolantRadTemp
125             CCAN__VCU_M2__CR_VCU_ActDmdTq
126          CCAN__VCU_M2__CR_VCU_DriverDmdTq
Name: SignalName, Length: 127, dtype: object

In [ ]:
sig2 = useful_excel2['SignalName']
print(sig2.head(),'\n AuxInv 길이:',len(sig2))  # AuxInv

0        BM1__AxuInverter__Inv_Battery_V
1      BM1__AxuInverter__INV_Fault_Check
2         BM1__AxuInverter__Inv_IptVol_V
3         BM1__AxuInverter__INV_Power_kW
4    BM1__AxuInverter__Mot_ActRotSpd_rpm
Name: SignalName, dtype: object 
 AuxInv 길이: 25


In [ ]:
sig3 = useful_excel3['SignalName']
print(sig3.head(),'\n BMS 길이:',len(sig3))  # BMS

0            BM1__BMS10__CR_Bms_BulkSOC
1       BM1__BMS10__CR_Bms_EvEnergyCapa
2    BM1__BMS10__CR_Bms_EVTargetCurrent
3       BM1__BMS10__CR_Bms_EVTargetVolt
4            BM1__BMS10__CR_Bms_FullSOC
Name: SignalName, dtype: object 
 BMS 길이: 339


In [ ]:
sig4 = useful_excel4['SignalName']
print(sig4.head(),'\n EBS 길이:',len(sig4))  # EBS

0       CCAN__CVW__GrossCombinationVehicleWeight
1                CCAN__CVW__PoweredVehicleWeight
2    CCAN__DM1_EBS__AmberWarningLampStatus_EBS_C
3                      CCAN__DM1_EBS__DTC1_EBS_C
4                      CCAN__DM1_EBS__DTC2_EBS_C
Name: SignalName, dtype: object 
 EBS 길이: 143


In [ ]:
sig5 = useful_excel5['SignalName']
print(sig5.head(),'\n MCU 길이:',len(sig5))  # MCU

0    BM1__DM1_MCU_L__AmberWarningLampStatus_MCU_L_B
1                      BM1__DM1_MCU_L__DTC1_MCU_L_B
2                      BM1__DM1_MCU_L__DTC2_MCU_L_B
3                      BM1__DM1_MCU_L__DTC3_MCU_L_B
4                      BM1__DM1_MCU_L__DTC4_MCU_L_B
Name: SignalName, dtype: object 
 MCU 길이: 66


In [ ]:
sig6 = useful_excel6['SignalName']
print(sig6.head(),'\n VCU 길이:',len(sig6))  # VCU

0    BM1__DM1_VCU__AmberWarningLampStatus_VCU_B
1                      BM1__DM1_VCU__DTC1_VCU_B
2                      BM1__DM1_VCU__DTC2_VCU_B
3                      BM1__DM1_VCU__DTC3_VCU_B
4                      BM1__DM1_VCU__DTC4_VCU_B
Name: SignalName, dtype: object 
 VCU 길이: 157


In [ ]:
print(len(sig1)+len(sig2)+len(sig3)+len(sig4)+len(sig5)+len(sig6))
print(len(set(sig1)|set(sig2)|set(sig3)|set(sig4)|set(sig5)|set(sig6)))
set(sig1)&set(sig2)&set(sig3)&set(sig4)&set(sig5)&set(sig6)

857
730


set()

In [ ]:
# 휠모터 고장 연관 채널(sig1) + 다른 sheet 변수명(sig2~sig6) 교집합
print('1:',set(sig1)&set(sig2)) 
print('2:',set(sig1)&set(sig3))
print('3:',set(sig1)&set(sig4))
print('4:',set(sig1)&set(sig5))
print('5:',set(sig1)&set(sig6))

1: {'BM1__AxuInverter__Mot_TKO_Sensor', 'BM1__AxuInverter__Inv_Battery_V', 'BM1__AxuInverter__Mot_APU_Sensor', 'BM1__AxuInverter__Mot_ActRotSpd_rpm', 'BM1__AxuInverter__INV_Power_kW', 'BM1__AxuInverter__MotInv_Mode_Status', 'BM1__AxuInverter__MotInvRdy', 'BM1__AxuInverter__Mot_APU_Stats', 'BM1__AxuInverter__MotInv_Temp_C', 'BM1__AxuInverter__INV_Fault_Check', 'BM1__AxuInverter__Inv_IptVol_V', 'BM1__AxuInverter__Mot_PRE_Sensor', 'BM1__AxuInverter__Mot_CtrMod'}
2: {'BM1__BMS10__CR_Bms_BulkSOC', 'BM1__BMS10__CR_Bms_FullSOC', 'BM1__BMS10__CR_Bms_EVTargetCurrent', 'BM1__BMS10__CR_Bms_EVTargetVolt', 'BM1__BMS11__CR_Bms_BatTotV_V', 'BM1__BMS10__CR_Bms_EvEnergyCapa'}
3: {'CCAN__EBC1__EngRetarderSelection', 'CCAN__EBC1__EBSBrakeSwitch', 'CCAN__EBC1__BrakePedalPos', 'CCAN__HRW__RearAxleRightWheelSpeed', 'CCAN__HRW__RearAxleLeftWheelSpeed'}
4: {'BM1__MCU_R1__MotoringTorqueUpperLimit', 'BM1__DM1_MCU_L__RedStopLampState_MCU_L_B', 'BM1__MCU_L2__ActualMotorRotationSpeed', 'BM1__DM1_MCU_L__FlashMalfun

In [ ]:
print('1:',len(set(sig1)&set(sig2)))
print('2:',len(set(sig1)&set(sig3)))
print('3:',len(set(sig1)&set(sig4)))
print('4:',len(set(sig1)&set(sig5)))
print('5:',len(set(sig1)&set(sig6)))

1: 13
2: 6
3: 5
4: 66
5: 37


In [ ]:
13+6+5+66+37 
# 휠모터고장연관채널 sheet는 각 sheet별로 고장에 제일 연관되어 보이는 것들만 뽑아 놓은 것

127

### 해당 채널 탐색

In [ ]:
final_set = set(sig1)|set(sig2)|set(sig3)|set(sig4)|set(sig5)|set(sig6)
final_name = list(final_set)
final_name[:5] # 선정된 채널 이름들

['BM1__BMS_M1_CellVol__Cell_Vol3_Index',
 'BM1__BMS_S1_2__CR_Bms_BatI_A',
 'BM1__BMS4__CF_BMS_FltForCCM',
 'CCAN__RQST_VCU__CR_VCU_ReqPGN',
 'BM1__BMS9__CF_Bms_RlyWeldDetectionReq']

* 15일 mat file 탐색

In [ ]:
set(test.columns)&final_set # 15일 파일중 해당하는 채널은 1개

In [ ]:
test['CCAN__XBR1__CR_VCU_XBRUrgency'].iloc[0][0][0]

240.1399

In [ ]:
test[test.columns[0]][0][0]

array([2.40131550e+02, 2.01211479e-01])

In [ ]:
test[test.columns[0]][0]

array([[2.40131550e+02, 2.01211479e-01],
       [2.40141650e+02, 2.01211479e-01],
       [2.40151550e+02, 2.01211479e-01],
       ...,
       [3.01458350e+02, 8.98832970e-02],
       [3.01468350e+02, 8.98832970e-02],
       [3.01478350e+02, 8.98832970e-02]])

In [ ]:
test.iloc[:,np.argmin(col_len)][0]

array([], shape=(0, 2), dtype=float64)

In [ ]:
test.iloc[:,np.argmax(col_len)][0]

array([[240.1402 ,   0.     ],
       [240.1497 ,   0.     ],
       [240.1597 ,   0.     ],
       ...,
       [301.4632 ,   0.     ],
       [301.4732 ,   0.     ],
       [301.48315,   0.     ]])

In [ ]:
test['CCAN__VDC2_EBS__SteerWheelAngleSensorType'].iloc[0]

array([[240.13155,   3.     ],
       [240.14165,   3.     ],
       [240.15155,   3.     ],
       ...,
       [301.45835,   3.     ],
       [301.46835,   3.     ],
       [301.47835,   3.     ]])

* 14일 mat file 탐색

In [ ]:
def main_search(n):
  path_dir = '/content/gdrive/MyDrive/DATA/고장코드 有_변환 후/45.동남_1643_200928_P1F2086'
  file_list = os.listdir(path_dir)
  matfile14=[]
  date = file_list[n]
  dist = path_dir+'/'+date # file_list 1~6까진 분할파일에서 얻어야 함 (file size때문)
  matfile14.append(io.loadmat(dist)) # 14일 21 19 13
  feature_name = [] 
  global main_test
  main_test = pd.DataFrame(matfile14)
  col_len=[]
  for i in range(len(main_test.T)):
    col_len.append(len(main_test.iloc[0,i]))
  global max_timelen_file
  max_timelen_file = []  
  max_timelen_file.append(main_test.iloc[:,np.argmax(col_len)].iloc[0]) # 해당 일자 data중 최대 길이 시간 길이인 채널 따로 저장
  selected_chan = set(main_test.columns)&final_set # 해당 파일중 선정된 채널에 해당하는 것 (column 교집합)
  print(dist) # 파일 주소 출력
  print(len(pd.DataFrame(matfile14).T)) # 데이터프레임 길이(채널 갯수)
  print(date)   # 날짜 표시
  print(max(col_len)) # 채널 중 최대 시간 길이
  print(len(selected_chan)) # 해당 채널의 총 길이
  global selected_df
  selected_df = main_test[selected_chan]

In [ ]:
def wheel_search(n):
  path_dir = '/content/gdrive/MyDrive/DATA/고장코드 有_변환 후/27.진해_6033_200115_P1F0166,0066'
  file_list = os.listdir(path_dir)
  matfile14=[]
  date = file_list[n]
  dist = path_dir+'/'+date # file_list 1~6까진 분할파일에서 얻어야 함 (file size때문)
  matfile14.append(io.loadmat(dist)) # 14일 21 19 13
  global wheel_test
  wheel_test = pd.DataFrame(matfile14)
  col_len=[]
  for i in range(len(wheel_test.T)):
    col_len.append(len(wheel_test.iloc[0,i]))
  global max_timelen_file2
  max_timelen_file2 = []  
  max_timelen_file2.append(wheel_test.iloc[:,np.argmax(col_len)].iloc[0]) # 해당 일자 data중 최대 길이 시간 길이인 채널 따로 저장
  selected_chan = set(wheel_test.columns)&set(sig1) # 해당 파일중 wheel모터 고장 채널과의 교집합 
  print(dist) # 파일 주소 출력
  print(len(pd.DataFrame(matfile14).T)) # 데이터프레임 길이(채널 갯수)
  print(date)   # 날짜 표시
  print(max(col_len)) # 채널 중 최대 시간 길이
  print(len(selected_chan)) # 해당 채널의 총 길이
  global wheel_df
  wheel_df = wheel_test[selected_chan].T
  return wheel_df

In [ ]:
# hi_1 = set(wheel_search(0).T.columns)
# hi_2 = set(wheel_search(11).T.columns)
# hi_1&hi_2

/content/gdrive/MyDrive/DATA/고장코드 有_변환 후/27.진해_6033_200115_P1F0166,0066/분할/진해_6033_20200114191610_1.mat
631
진해_6033_20200114191610_1.mat
709706
43


In [ ]:
wheel_search(8)

/content/gdrive/MyDrive/DATA/고장코드 有_변환 후/27.진해_6033_200115_P1F0166,0066/진해_6033_20200115044101.mat
609
진해_6033_20200115044101.mat
1484
32


0
CCAN__EMRC1__CR_Vcu_Em1ActMaxAvailRtdTq     [[240.45275, 0.0], [240.46365, 0.0], [240.4727...
CCAN__EMRC1__CR_Vcu_Em1ActPerTorq           [[240.45275, 0.0], [240.46365, 0.0], [240.4727...
CCAN__EEC2__CR_VCU_AccelPedPos              [[240.46275, 0.0], [240.48265, 0.0], [240.5027...
CCAN__EMRC1__CR_Vcu_Em1RtdPerTorq           [[240.45275, 0.0], [240.46365, 0.0], [240.4727...
CCAN__ETC2__CR_VCU_SelGear                  [[240.54365, 0.0], [240.64365, 0.0], [240.7436...
CCAN__VCU_CLUINF1__CF_VCU_MotorOverTemp                    [[240.5451, 0.0], [240.6451, 0.0]]
BM1__BMS10__CR_Bms_EVTargetVolt             [[241.20325, 0.0], [241.30325, 0.0], [241.4032...
CCAN__EMRC1__CR_Vcu_Em1RtdSelect            [[240.45275, 0.0], [240.46365, 0.0], [240.4727...
BM1__BMS10__CR_Bms_EvEnergyCapa             [[241.20325, 64000.0], [241.30325, 64000.0], [...
CCAN__VCU_M2__CR_VCU_DriverDmdTq            [[240.45305, 0.0], [240.46395, 0.0], [240.4730...
CCAN__EEC1__CR_VCU_EngineSpd                [[240.4522, 0.0], [240.4622, 0.0], [240.4722, ...
CCAN__VCU_CLUINF1__CR_VCU_CoolantTemp                      [[240.5451, 0.0], [240.6451, 0.0]]
CCAN__ETC1__CR_VCU_ShiftInProcess           [[240.4519, 0.0], [240.4619, 0.0], [240.4719, ...
CCAN__ETC2__CR_VCU_TransCurrentGear         [[240.54365, 0.0], [240.64365, 0.0], [240.7436...
CCAN__ETC1__CR_VCU_DrivelineEng             [[240.4519, 0.0], [240.4619, 0.0], [240.4719, ...
BM1__BMS10__CR_Bms_FullSOC                  [[241.20325, 0.0], [241.30325, 0.0], [241.4032...
CCAN__VCU_CLUINF1__CF_VCU_VCUFault                         [[240.5451, 0.0], [240.6451, 0.0]]
BM1__BMS11__CR_Bms_BatTotV_V                [[241.2035, 0.0], [241.3035, 0.0], [241.40345,...
CCAN__ETC2__CR_VCU_TrasmCurRange            [[240.54365, 78.0], [240.64365, 78.0], [240.74...
CCAN__EMRC1__CR_Vcu_Em1CtrlDevice           [[240.45275, 239.0], [240.46365, 239.0], [240....
CCAN__ETC1__CR_VCU_OutputShaftSpd           [[240.4519, 0.0], [240.4619, 0.0], [240.4719, ...
CCAN__EMRC1__CR_Vcu_Em1ActPctTqHiRes        [[240.45275, 0.0], [240.46365, 0.0], [240.4727...
CCAN__EMRC1__CR_Vcu_Em1TorqMode             [[240.45275, 14.0], [240.46365, 14.0], [240.47...
CCAN__ETC1__CR_VCU_InputShaftSpd            [[240.4519, 0.0], [240.4619, 0.0], [240.4719, ...
CCAN__VCU_CLUINF1__CF_VCU_MCUInverterFault                 [[240.5451, 0.0], [240.6451, 0.0]]
BM1__BMS10__CR_Bms_BulkSOC                  [[241.20325, 154.0], [241.30325, 154.0], [241....
BM1__BMS10__CR_Bms_EVTargetCurrent          [[241.20325, 0.0], [241.30325, 0.0], [241.4032...
CCAN__ETC2__CR_VCU_TrasmReqRange            [[240.54365, 78.0], [240.64365, 78.0], [240.74...
CCAN__EMRC1__CR_Vcu_Em1MotOutShaftSpd       [[240.45275, 0.0], [240.46365, 0.0], [240.4727...
CCAN__EEC2__CR_VCU_AccelPedPos2             [[240.46275, 0.0], [240.48265, 0.0], [240.5027...
CCAN__VCU_CLUINF1__CR_VCU_MotorPower_Per                   [[240.5451, 0.0], [240.6451, 0.0]]
CCAN__VCU_M2__CR_VCU_ActDmdTq               [[240.45305, 77.0], [240.46395, 77.0], [240.47...

In [ ]:
wheel_search(2).to_excel(excel_writer='Daejin_wheel.xlsx') # 최소갯수 추출

/content/gdrive/MyDrive/DATA/고장코드 有_변환 후/41.대진_1872_200803_P1F2806/대진_1872_20200803092814.mat
521
대진_1872_20200803092814.mat
63
6


In [ ]:
main_search(7) # 함수 주소의 해당 폴더 n번째 파일

/content/gdrive/MyDrive/DATA/고장코드 有_변환 후/45.동남_1643_200928_P1F2086/동남_1643_20200928164616.mat
1184
동남_1643_20200928164616.mat
23343
668


In [ ]:
max_timelen_file[0][0],max_timelen_file[0][-1]

(array([240.11185,   0.     ]), array([301.7644,   0.    ]))

In [ ]:
max_timelen_file[0]

array([[240.02275,   0.     ],
       [240.0328 ,   0.     ],
       [240.04285,   0.     ],
       ...,
       [507.67895,   0.     ],
       [507.68895,   0.     ],
       [507.699  ,   0.     ]])

In [ ]:
# pd.DataFrame(main_test.columns).to_excel(excel_writer='sample.xlsx')

In [ ]:
selected_df

CCAN__TSC1_290B__EngineRequestedTorqueHiRes  ...                        BM1__BMS9__CF_Bms_Fail_Temp
0  [[240.0775, 1.875], [240.2775, 1.875], [240.47...  ...  [[241.0482, 0.0], [241.1482, 0.0], [241.2482, ...

[1 rows x 730 columns]

In [ ]:
print(len(main_test['CCAN__XBR1__CR_VCU_XBRUrgency'].iloc[0])) # 해당 채널 데이터 길이
main_test['CCAN__XBR1__CR_VCU_XBRUrgency'].iloc[0]

223091


array([[ 240.0497 ,    0.     ],
       [ 240.06965,    0.     ],
       [ 240.08965,    0.     ],
       ...,
       [4702.0492 ,    0.     ],
       [4702.06925,    0.     ],
       [4702.0892 ,    0.     ]])

In [ ]:
pd.DataFrame(main_test['CCAN__XBR1__CR_VCU_XBRUrgency'].iloc[0])

In [ ]:
np.unique(pd.DataFrame(main_test['CCAN__XBR1__CR_VCU_XBRUrgency'].iloc[0])[1])

array([0.])

### 무고장

In [ ]:
def main_mu(n):
  path_dir = '/content/gdrive/MyDrive/DATA/무고장데이터_5일간/27.진해_6033_200110_200114_5일간'
  file_list = os.listdir(path_dir)
  matfile=[]
  date = file_list[n]
  dist = path_dir+'/'+date # file_list 1~6까진 분할파일에서 얻어야 함 (file size때문)
  matfile.append(io.loadmat(dist)) #무고장
  feature_name = [] 
  global main_mu
  main_df = pd.DataFrame(matfile)
  print(dist) # 파일 주소 출력
  print(date)   # 날짜 표시
  return main_df

In [ ]:
mu_2 = main_mu(1)
mu_2.head()

/content/gdrive/MyDrive/DATA/무고장데이터_5일간/27.진해_6033_200110_200114_5일간/진해_6033_20200111053415.mat
진해_6033_20200111053415.mat


CCAN__HRW__FrontAxl  ...                                BM1__CMM4_BM2__CF_E
0  [[240.369, 0.0], [240.3892, 0.0], [240.40905, ...  ...  [[7247.65325, 0.0], [7247.7532, 0.0], [7247.85...

[1 rows x 510 columns]

In [ ]:
set(mu_2.columns)&final_set

set()

### dd

In [ ]:
useful_index = []
for idx in range(0, len(matfile1)): # feature가 각각 142,1142,1142,1142 서로 다른 길이의 파일 총 4개 에서 for문
    useful_idx = []  # 빈 리스트 4개 생성
    for idx2, keys in enumerate(feature_name[idx]): # 142,1142,1142,1142개의 항목... 각 idx와 key값(피처이름)
        length = show_duplicate(matfile1[idx][keys]) 
        if length > 1 :
            useful_idx.append((idx2,length, len(matfile1[idx][keys])))
    useful_index.append(useful_idx)    

In [ ]:
useful_index[0] # [0~3]까지 총 4항목 존재
# 각각의 값은 tuple형태로 저장되어있고 각 값의 의미는... 순서대로
# (1. feature가있는 위치(feature index), 2. unique한 값 갯수 , 3. 해당 feature의 전체 data수)

In [ ]:
useful_col=[]
for s in useful_index[0]:
    useful_col.append(s[0])
print(len(useful_col))

In [ ]:
pd.DataFrame(matfile1).T.iloc[useful_col] # useful한 column들만 남겨놓는다.

In [ ]:
useful_df = pd.DataFrame(matfile1).T.iloc[useful_col]

### DTC 추출

In [ ]:
import re
p = re.compile('.*DTC1.*')
dtc_set = []
for f_name in feature_name:
    dtc_index = []
    for idx, name in enumerate(f_name):
        m = p.match(name)
        if m != None:
            print(m.group())
            dtc_index.append(idx)
    dtc_set.append(dtc_index)

In [ ]:
for i in dtc_set:
    print(len(i))
    print(dtc_set[0])

In [ ]:
dtc_name = [] # 이름 list
for i in range(len(dtc_set)):
  print(i+1,'번째 파일의 dtc이름 및 index')
  for dtc in dtc_set[i]:
    print(dtc,feature_name[0][dtc])
    dtc_name.append(feature_name[0][dtc])

In [ ]:
matfile13[0]['CCAN__DM1_DOD__DTC1_DOD_B']

In [ ]:
DTC_df_1 = pd.DataFrame(matfile1)[dtc_name].T
DTC_df_1

In [ ]:
DTC_df_1[0].iloc[2]

In [ ]:
for i in range(len(DTC_df_1)): # DTC 피쳐별로 데이터 개수가 다름(수집 시간 차이?)
  print(len(DTC_df_1[0].iloc[i]))

In [ ]:
def float_to_hex(f):
    return hex(struct.unpack('<I', struct.pack('<f', f))[0])

In [ ]:
len(DTC_df_1)

In [ ]:
dtc_col = []
dtc_val = []
for i in range(len(DTC_df_1)):
  dtc_col.append(DTC_df_1.index[i]) # DTC Feature 이름
  dtc_val.append(DTC_df_1[0].iloc[i][:,1]) # value 2-d array의 i번째 인덱스의 두번째값(실제 value)

In [ ]:
pd.DataFrame(dtc_val,dtc_col).T

> NAN값 없는 범위에 대해서만 생성

In [ ]:
dtc_df = pd.DataFrame(dtc_val,dtc_col).T[:6898]

In [ ]:
dtc_df = dtc_df[:6898]

In [ ]:
dtc_hex_df = dtc_df

In [ ]:
dtc_hex_df

In [ ]:
for i in dtc_hex_df.columns:
  dtc_hex_df[i] = dtc_hex_df[i].apply(float_to_hex)
dtc_hex_df

# **고장코드 無 변환 후**

In [ ]:
path_dir = '/content/gdrive/MyDrive/DATA/무고장데이터_5일간/27.진해_6033_200110_200114_5일간'
file_list13 = os.listdir(path_dir)

In [ ]:
file_list13 = file_list[-20:-8] # 13일 
file_list13

In [ ]:
matfile13 = []
count = 0
for file in file_list13:
    dist = path_dir + '/' + file
    count+=1
    if count==1: 
      matfile13.append(io.loadmat(dist)) # 13일 첫번째 파일


In [ ]:
pd.DataFrame(matfile13).T[0]

In [ ]:
feature_name = []
for file in matfile13:
    feature_name.append(list(file.keys()))

for i in feature_name:
    print(len(i))

In [ ]:
time = []
for i in range(len(pd.DataFrame(matfile13).T[0])):
  time.append(pd.DataFrame(matfile13).T[0].iloc[i][-1][0])
print(max(time))

In [ ]:
pd.DataFrame(matfile13).T[0].iloc[2][-1][0]